export const events = [
    {
        slug: "cityjs-london-2026",
        image: "/images/event1.png",
        title: "CityJS London 2026",
        location: "London, UK",
        date: "April 15-17, 2026",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "jsworld-conference-2026",
        image: "/images/event2.png",
        title: "JSWorld Conference",
        location: "Amsterdam, Netherlands",
        date: "May 7-8, 2026",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "agentic-ai-bootcamp",
        image: "/images/event3.png",
        title: "NCHC LLM & Agentic AI Bootcamp",
        location: "Hsinchu, Taiwan",
        date: "May 20, 2026",
        time: "10:00 AM - 5:00 PM",
    },
    {
        slug: "tacc-open-hackathon",
        image: "/images/event4.png",
        title: "TACC HPC + AI Hackathon",
        location: "Austin, TX (Hybrid)",
        date: "May 20-29, 2026",
        time: "Flexible Hours",
    },
    {
        slug: "princeton-ai-hackathon",
        image: "/images/event5.png",
        title: "Princeton Open AI Hackathon",
        location: "Princeton, NJ",
        date: "May 26 - June 4, 2026",
        time: "9:00 AM - 8:00 PM",
    },
    {
        slug: "cineca-gpu-hackathon",
        image: "/images/event6.png",
        title: "CINECA GPU Hackathon",
        location: "Bologna, Italy (Virtual)",
        date: "June 30 - July 8, 2026",
        time: "24 Hours",
    },
    {
        slug: "nersc-hpc-ai-event",
        image: "/images/event1.png",
        title: "NERSC Open Hackathon",
        location: "Berkeley, CA (Hybrid)",
        date: "August 18-28, 2026",
        time: "9:00 AM - 5:30 PM",
    },
    {
        slug: "helmholtz-gpu-2026",
        image: "/images/event2.png",
        title: "Helmholtz GPU Hackathon",
        location: "Jülich, Germany",
        date: "September 2-11, 2026",
        time: "9:30 AM - 6:00 PM",
    },
    {
        slug: "react-india-final",
        image: "/images/event3.png",
        title: "React India: The Final Edition",
        location: "Goa, India",
        date: "October 29-31, 2026",
        time: "8:00 AM - 7:00 PM",
    },
    {
        slug: "marenostrum-hackathon",
        image: "/images/event4.png",
        title: "8th Marenostrum AI Hackathon",
        location: "Barcelona, Spain",
        date: "September 15-30, 2027",
        time: "72 Hours",
    },
];